In [1]:
import pandas as pd
import numpy as np

In [2]:
pm1=pd.read_excel("C:\\Users\\1-10\\Desktop\\미세먼지\\2017\\2017-1.xlsx")

In [3]:
pm2=pd.read_excel("C:\\Users\\1-10\\Desktop\\미세먼지\\2017\\2017-2.xlsx")

In [4]:
pm3=pd.read_excel("C:\\Users\\1-10\\Desktop\\미세먼지\\2017\\2017-3.xlsx")

In [5]:
pm4=pd.read_excel("C:\\Users\\1-10\\Desktop\\미세먼지\\2017\\2017-4.xlsx")

In [6]:
pm5=pd.read_excel("C:\\Users\\1-10\\Desktop\\미세먼지\\2018\\2018-1.xlsx")

In [7]:
pm6=pd.read_excel("C:\\Users\\1-10\\Desktop\\미세먼지\\2018\\2018-2.xlsx")

In [8]:
pm7=pd.read_excel("C:\\Users\\1-10\\Desktop\\미세먼지\\2018\\2018-3.xlsx")

In [9]:
pm8=pd.read_excel("C:\\Users\\1-10\\Desktop\\미세먼지\\2018\\2018-4.xlsx")

In [10]:
pm9=pd.read_excel("C:\\Users\\1-10\\Desktop\\미세먼지\\2019\\2019-1.xlsx")

In [11]:
pm10=pd.read_excel("C:\\Users\\1-10\\Desktop\\미세먼지\\2019\\2019-2.xlsx")

In [12]:
pm11=pd.read_excel("C:\\Users\\1-10\\Desktop\\미세먼지\\2019\\2019-3.xlsx")

In [13]:
pm12=pd.read_excel("C:\\Users\\1-10\\Desktop\\미세먼지\\2019\\2019-4.xlsx")

In [14]:
pm13=pd.read_excel("C:\\Users\\1-10\\Desktop\\미세먼지\\2019\\2019-5.xlsx")

In [15]:
pm14=pd.read_excel("C:\\Users\\1-10\\Desktop\\미세먼지\\2019\\2019-6.xlsx")

In [16]:
pm15=pd.read_excel("C:\\Users\\1-10\\Desktop\\미세먼지\\2019\\2019-7.xlsx")

In [17]:
pm16=pd.read_excel("C:\\Users\\1-10\\Desktop\\미세먼지\\2019\\2019-8.xlsx")

In [18]:
pm17=pd.read_excel("C:\\Users\\1-10\\Desktop\\미세먼지\\2019\\2019-9.xlsx")

In [19]:
df=pd.concat([pm1,pm2,pm3,pm4,pm5,pm6,pm7,pm8,pm9,pm10,pm11,pm12,pm13,pm14,pm15,pm16,pm17],sort=True)

In [30]:
df

,CO,NO2,O3,PM10,PM25,SO2,망,주소,지역,측정소명,측정소코드,측정일시,측정월,시,구,측정연도,측정일,측정시
0,1.3,0.068,0.002,77.0,63.0,0.006,NaN,서울 중구 덕수궁길 15,서울 중구,중구,111121,2017010101,01,서울,중구,2017,01,01
1,1.4,0.066,0.002,76.0,63.0,0.006,NaN,서울 중구 덕수궁길 15,서울 중구,중구,111121,2017010102,01,서울,중구,2017,01,02
2,1.2,0.063,0.002,73.0,57.0,0.005,NaN,서울 중구 덕수궁길 15,서울 중구,중구,111121,2017010103,01,서울,중구,2017,01,03
3,1.1,0.053,0.002,67.0,55.0,0.005,NaN,서울 중구 덕수궁길 15,서울 중구,중구,111121,2017010104,01,서울,중구,2017,01,04
4,1.1,0.051,0.002,66.0,54.0,0.004,NaN,서울 중구 덕수궁길 15,서울 중구,중구,111121,2017010105,01,서울,중구,2017,01,05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28795,0.8,0.084,0.008,55.0,32.0,0.004,도로변대기,서울 노원구 화랑로 429,서울 노원구,화랑로,111312,2019093020,09,서울,노원구,2019,30,20
28796,0.7,0.076,0.005,58.0,32.0,0.004,도로변대기,서울 노원구 화랑로 429,서울 노원구,화랑로,111312,2019093021,09,서울,노원구,2019,30,21
28797,0.7,0.070,0.005,55.0,30.0,0.004,도로변대기,서울 노원구 화랑로 429,서울 노원구,화랑로,111312,2019093022,09,서울,노원구,2019,30,22
28798,0.6,0.066,0.005,60.0,33.0,0.004,도로변대기,서울 노원구 화랑로 429,서울 노원구,화랑로,111312,2019093023,09,서울,노원구,2019,30,23
28799,0.6,0.059,0.006,59.0,33.0,0.004,도로변대기,서울 노원구 화랑로 429,서울 노원구,화랑로,111312,2019093024,09,서울,노원구,2019,30,24

In [29]:
df['시']=df['지역'].apply(lambda x : x[:2])

df['구']=df['지역'].apply(lambda x : x[3:6])

df['측정연도']=df['측정일시'].apply(lambda x : str(x)[:4])

df['측정월']=df['측정일시'].apply(lambda x : str(x)[4:6])

df['측정일']=df['측정일시'].apply(lambda x : str(x)[6:8])

df['측정시']=df['측정일시'].apply(lambda x : str(x)[8:])

df=df[df["시"]=="서울"]

C:\Users\1-10\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\1-10\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\1-10\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\1-10\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\1-10\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\Users\1-10\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

In [36]:
df

,CO,NO2,O3,PM10,PM25,SO2,망,주소,지역,측정소명,측정소코드,측정일시,측정월,시,구,측정연도,측정일,측정시
0,1.3,0.068,0.002,77.0,63.0,0.006,NaN,서울 중구 덕수궁길 15,서울 중구,중구,111121,2017010101,01,서울,중구,2017,01,01
1,1.4,0.066,0.002,76.0,63.0,0.006,NaN,서울 중구 덕수궁길 15,서울 중구,중구,111121,2017010102,01,서울,중구,2017,01,02
2,1.2,0.063,0.002,73.0,57.0,0.005,NaN,서울 중구 덕수궁길 15,서울 중구,중구,111121,2017010103,01,서울,중구,2017,01,03
3,1.1,0.053,0.002,67.0,55.0,0.005,NaN,서울 중구 덕수궁길 15,서울 중구,중구,111121,2017010104,01,서울,중구,2017,01,04
4,1.1,0.051,0.002,66.0,54.0,0.004,NaN,서울 중구 덕수궁길 15,서울 중구,중구,111121,2017010105,01,서울,중구,2017,01,05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28795,0.8,0.084,0.008,55.0,32.0,0.004,도로변대기,서울 노원구 화랑로 429,서울 노원구,화랑로,111312,2019093020,09,서울,노원구,2019,30,20
28796,0.7,0.076,0.005,58.0,32.0,0.004,도로변대기,서울 노원구 화랑로 429,서울 노원구,화랑로,111312,2019093021,09,서울,노원구,2019,30,21
28797,0.7,0.070,0.005,55.0,30.0,0.004,도로변대기,서울 노원구 화랑로 429,서울 노원구,화랑로,111312,2019093022,09,서울,노원구,2019,30,22
28798,0.6,0.066,0.005,60.0,33.0,0.004,도로변대기,서울 노원구 화랑로 429,서울 노원구,화랑로,111312,2019093023,09,서울,노원구,2019,30,23
28799,0.6,0.059,0.006,59.0,33.0,0.004,도로변대기,서울 노원구 화랑로 429,서울 노원구,화랑로,111312,2019093024,09,서울,노원구,2019,30,24

In [21]:
w=pd.read_csv("C:\\Users\\1-10\\Desktop\\미세먼지\\기상2017.csv",encoding = 'CP949')

In [23]:
w

     지점 지점명       일시  평균기온(°C)  월합강수량(00~24h만)(mm)  평균풍속(m/s)
0   108  서울  2017-01      -1.8                14.9        2.3
1   108  서울  2017-02      -0.2                11.1        2.4
2   108  서울  2017-03       6.3                 7.9        2.4
3   108  서울  2017-04      13.9                61.6        2.6
4   108  서울  2017-05      19.5                16.1        2.4
5   108  서울  2017-06      23.3                66.6        2.4
6   108  서울  2017-07      26.9               621.0        2.0
7   108  서울  2017-08      25.9               297.0        2.3
8   108  서울  2017-09      22.1                35.0        2.0
9   108  서울  2017-10      16.4                26.5        1.9
10  108  서울  2017-11       5.6                40.7        2.1
11  108  서울  2017-12      -1.9                34.8        1.8